services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_shop
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=157246qq#
      - MSSQL_PID=Developer
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - shop-network

networks:
  shop-network:
    driver: bridge

volumes:
  sql_data:
